name: Build FreeCHAT APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: android-actions/setup-android@v3
      - name: Install and Build
        run: |
          npm install
          npm run build || true
          npm install -D @capacitor/core @capacitor/cli @capacitor/android
          npx cap init FreeCHAT com.wizarddevis.freechat --web-dir=out || npx cap init FreeCHAT com.wizarddevis.freechat --web-dir=dist || npx cap init FreeCHAT com.wizarddevis.freechat --web-dir=build || true
          npx cap add android
          npx cap copy android || true
      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
         ./gradlew assembleDebug
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: FreeCHAT-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
